---
keys:
  - &users:
    - &franta age1dvj29v7swu6e0pw5t5mwpjscktts4d676a8lre7vpf995qf58aqqqy6c32
  - &hosts:
    - &nix-bastion age1an8jkd67y34aa3fzejsdcq27lfzsn74kn2qdnpzsjyhc9wcw5dqqhc7rhr
    - &qotom age1fku3as83dv8fcm0vm0ka2z7ckpcegvp4xanl8fjndmkprxfn54nsdrfc97
    - &lanthanum age1xc4sgp7yt7j0hy842kffqy2hpjxpwdn6f235l42s7tmdu0qkx4cs8uxxyc
    - &work-vm age1u2z93gyp7zek6cy5tuva3n4lm825rd3au8aqralx409jh9wm9gfsdsgdq3
    - &nixos-firewall age17zdm40vq8zwspqula4uhydjxe39ah0ltntj03ywjmzq4nglgednsv9sfr5
    - &r2s age1k4jcr5vnrvwl2s2sh2p3flejdcte0dsdt9daj6kwpwsc6r5t3sasuh33l4
    - &molybdenum age1en9r5jtv5cl7vfwlt9pjj5cmwck2uydnhscmydtncg9xaqt7l5msyg52u3
    - &nix-hetzner age1req8f3xmj706n3sy68zavrs4uexgsp4e5ejtpfqdszw5qw37fp9sjkwa8x
    - &nix-vps-cz age1zqggxdatjwcryu5qgr9ge0gewzvvfpjv630h4mmc9d6xunufcayq3xvg02
    - &silicium age1rtkde8zynkul4y7ufxwvs2axp842u4wexynn9ypf8zv7egzs8azs5ue8je
    # age-plugin-yubikey -g -f --touch-policy cached --pin-policy never --slot 2 --name age-sops-nix
    - &NC312237 age1yubikey1qt2ve24yxkrvzuagxzjjp4lud44k4fwfw38345q0q7lveuyla3upjw9mjgm
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *nix-bastion
          - *qotom
          - *lanthanum
          - *work-vm
          - *nixos-firewall
          - *r2s
          - *molybdenum
          - *nix-hetzner
          - *nix-vps-cz
          - *silicium
  - path_regex: hosts/qotom/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *qotom
  - path_regex: hosts/nixos-firewall/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *nixos-firewall
  - path_regex: hosts/nix-bastion/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *nix-bastion
  - path_regex: hosts/lanthanum/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *lanthanum
  - path_regex: hosts/r2s/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *r2s
  - path_regex: hosts/molybdenum/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *molybdenum
  - path_regex: hosts/nix-hetzner/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *nix-hetzner
  - path_regex: hosts/nix-vps-cz/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *nix-vps-cz
  - path_regex: hosts/silicium/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *silicium
  - path_regex: home/fbartik/secrets.ya?ml$
    key_groups:
      - age:
          - *franta
  - path_regex: home/fbartik/nix-bastion-secrets.ya?ml$
    key_groups:
      - age:
          - *franta
          - *nix-bastion
  - path_regex: home/fbartik/NC312237-secrets.ya?ml$
    key_groups:
      - age:
          - *NC312237
