---
name: Update Flake Inputs

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  update-flake-inputs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: https://github.com/actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          owner: frantathefranta
          github-api-url: https://api.github.com
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Cache
        uses: https://code.forgejo.org/actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.cache/nix
          key: nix-${{ hashFiles('flake.lock') }}
          restore-keys: nix-

      - name: Configure git identity
        run: |
          git config --global user.email "lol@franta.us"
          git config --global user.name "lordoflightning-bot"
          git config --global init.defaultBranch main

      - name: Install nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Update flake inputs
        uses: https://git.franta.us/franta/update-flake-inputs-forgejo@fc557b3e9467d2e02854166fa1ea62375d668b6b
        with:
          forgejo-token: ${{ secrets.MERGE_TOKEN }}
          github-token: ${{ steps.app-token.outputs.token }}
          git-author-name: "lordoflightning-bot"
          git-author-email: "lol@franta.us"
          git-committer-name: "lordoflightning-bot"
          git-committer-email: "lol@franta.us"
          git-signing-key: ${{ secrets.BOT_SSH_KEY }}
          git-signing-pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIETVN3DTYcb+pWcX0JR4c2DYvA24lImxVknWPUW2gPzH"
          auto-merge: 'true'
          delete-branch: 'false'
