# -*- mode: bird -*-
template bgp collector {
  local as OWNAS;
  # enable multihop as the collector is not locally connected
  multihop;
  ipv4 {
    # export all available paths to the collector
    add paths tx;

    # import/export filters
    import none;
    export filter {
      # export all valid routes
      if ( is_valid_network() && source ~ [ RTS_STATIC, RTS_BGP ] )
      then {
        accept;
      }
      reject;
    };
  };

  ipv6 {
    # export all available paths to the collector
    add paths tx;

    # import/export filters
    import none;
    export filter {
      # export all valid routes
      if ( is_valid_network_v6() && source ~ [ RTS_STATIC, RTS_BGP ] )
      then {
        accept;
      }
      reject;
    };
  };
}

protocol bgp ROUTE_COLLECTOR from collector {
  neighbor fd42:d42:d42:179::1 as 4242422602;
}

protocol bgp nedifinita_collector from collector {
  neighbor fd10:127:42::179 as 4204549998 port 1179;
}
