# -*- mode:bird -*-
protocol device {
  scan time 10;
}

protocol direct {
  interface LOOPBACK;
  ipv6;
}

protocol kernel {
  scan time 20;
  ipv6 {
    import none;
    export filter {
      if source = RTS_STATIC then reject;
      krt_prefsrc = OWNIPv6;
      accept;
    };
  };
};

protocol kernel {
  scan time 20;
  ipv4 {
    import none;
    export filter {
      if source = RTS_STATIC then reject;
      krt_prefsrc = OWNIP;
      accept;
    };
  };
}

protocol static {
  route OWNNETv6 reject;
  ipv6 {
    import all;
    export none;
  };
}

protocol static {
  route OWNNET reject;
  ipv4 {
    import all;
    export none;
  };
}

protocol bfd {}

protocol ospf v3 OSPF6 {
  ipv6 {
    export filter {
      if is_loopback_v6() && source != RTS_BGP then accept;
    };
  };

  area 0 {
    interface LOOPBACK {
      stub;
    };

    interface "ibgp_*" {
      type pointopoint;
      # bfd on;
    };
  };
}

# protocol ospf v3 OSPF4 {
#   ipv4 {
#     export filter {
#       if source = RTS_STATIC || source = RTS_BGP then reject;
#       accept;
#     };
#   };

#   area 0 {
#     interface LOOPBACK {
#       stub;
#     };

#     interface "ibgp_*"{
#       type pointopoint;
#       # bfd on;
#     };
#   };
# }
