# -*- mode: bird -*-
roa4 table dn42_roa;
roa6 table dn42_roa_v6;

protocol rpki {
        roa4 { table dn42_roa; };
        roa6 { table dn42_roa_v6; };
        remote "::1";
        port 8282;
        refresh 600;
        retry 300;
        expire 7200;
}
