log stderr all;

define OWNAS =  65000;
define OWNIP =  10.0.0.1;
router id OWNIP;

# Device protocol gets information about interfaces (to be used in Direct protocol)
protocol device device1 {
  scan time 10;
}

# Direct protocol imports directly connected routes (to be used in Kernel protocol)
protocol direct direct1 {
  interface "lan0*";
  # interface "lan0*", "wan0";
  ipv4;
  ipv6;
}

protocol kernel kernel_v4 {
  ipv4 {
    import all;
    export all;
    # export filter {
    #   if ifname = "wan0" && net != 0.0.0.0/0 then reject;
    #   accept;
    # };
  };
}

protocol kernel kernel_v6 {
  ipv6 {
    import all;
    export all;
    # export filter {
    #   if ifname = "wan0" && net != ::/0 then reject;
    #   accept;
    # };
  };
}

protocol bgp arista {
  neighbor fe80::464c:a8ff:fede:3cf7%lan0 as 65033;
  local as OWNAS;
  ipv4 {
    extended next hop on;
    next hop self;
    import all;
    export all;
  };
  ipv6 {
    extended next hop on;
    next hop self;
    import all;
    export all;
  };
}
