log stderr all;

define OWNAS =  65000;
define OWNIP =  10.0.0.1;
router id OWNIP;
protocol device device1 {
  scan time 10;
}

protocol bgp arista {
  neighbor fe80::464c:a8ff:fede:3cf7%lan0 as 65033;
  ipv4 {
    extended next hop on;
    next hop self;
  };
  ipv6 {
    next hop self;
  };
}
