protocol bgp ROUTE_COLLECTOR
 {
  local as 4242421033;
  neighbor fd42:d42:d42:179::1 as 4242422602;

  # enable multihop as the collector is not locally connected
  multihop;

  ipv4 {
    # export all available paths to the collector
    add paths tx;

    # import/export filters
    import none;
    export filter {
      # export all valid routes
      if ( is_valid_network() && source ~ [ RTS_STATIC, RTS_BGP ] )
      then {
        accept;
      }
      reject;
    };
  };

  ipv6 {
    # export all available paths to the collector
    add paths tx;

    # import/export filters
    import none;
    export filter {
      # export all valid routes
      if ( is_valid_network_v6() && source ~ [ RTS_STATIC, RTS_BGP ] )
      then {
        accept;
      }
      reject;
    };
  };
}
protocol bgp iBGP_cmh from dnpeers {
  neighbor fdb7:c21f:f30f::1 as 4242421033;
  bfd on;
  source address OWNIPv6;
  ipv4 {
    extended next hop on;
    next hop self;
    import all;
    export where dn42_export_filter(4,25,34);
    import keep filtered;
  };
  ipv6 {
    extended next hop on;
    next hop self;
    import all;
    export where dn42_export_filter(4,25,34);
    import keep filtered;
  };
}
protocol bgp iBGP_prg from dnpeers {
  neighbor fdb7:c21f:f30f:2::1 as 4242421033;
  bfd on;
  source address OWNIPv6;
  ipv4 {
    extended next hop on;
    next hop self;
    import all;
    export where dn42_export_filter(6,25,34);
    import keep filtered;
  };

  ipv6 {
    extended next hop on;
    next hop self;
    import all;
    export where dn42_export_filter(6,25,34);
    import keep filtered;
  };
}
