---
name: Update Flake Inputs

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  update-flake-inputs:
    runs-on: ubuntu
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: ~/.cache/nix
          key: nix-${{ hashFiles('flake.lock') }}
          restore-keys: nix-

      - name: Install nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Update flake inputs
        uses: https://github.com/mfenniak/update-flake-inputs-forgejo@b5614c72bdce961524fe3ca2daad7de2d2d8f46f
        with:
          # gitea-token: ${{ secrets.GITEA_TOKEN }}
          github-token: ${{ secrets.RO_GITHUB_TOKEN }}
          git-author-name: "lordoflightning-bot"
          git-author-email: "lol@franta.us"
          git-committer-name: "lordoflightning-bot"
          git-committer-email: "lol@franta.us"
          auto-merge: 'false'
          delete-branch: 'true'
