---
on:
  push:
    branches: ["main"]

jobs:
  check-flake:
    runs-on: ubuntu
    steps:
      - name: Checkout Repository
        uses: https://github.com/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            extra-platforms = aarch64-linux
      - name: Check
        run: |
          nix flake check
