---
on:
  push:
    branches: ["main"]

jobs:
  check-flake:
    runs-on: native
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Check
        run: |
          nix flake check
